typography_spectrum: 0.48965
color:
  brandColors:
    - '#000000'
    - '#3a3a32'
    - '#cbb39b'
    - '#a87843'
    - '#81542c'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: unconditionyou@gmail.com
  name: Marco
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3c66812-9099-4ca8-9853-71f6891f4371.png
name: UnconditionYou
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 09e0b7e5-eead-4090-a785-2d2ac8fe0555
    url: 2016-04-01-credentials.html
    name: Credentials
    type: content
  - id: a4b4b907-ae7b-44c3-b531-a1033869ce3c
    url: 2016-04-01-fees.html
    name: Fees
    type: content
favicon: null
title: SPIRITUAL & EMOTIONAL COUNSELLING – DETOXIFICATION & HEALTH CONSULTATIONS
purpose: []
